theme: jekyll-theme-leap-day
title: Lazy Results
description: Jackson datatype module for Result
current_version: 0.2.0.1
show_downloads: true
logo: https://dev.leakyabstractions.com/result/result-banner.png
