
# Continuous Integration
name: Build

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - main
    - develop
    - jreleaser

jobs:
  build:

    name: Build on JDK${{ matrix.jdk }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        jdk: [ 23 ]

    env:
      is_latest_jdk:  ${{ matrix.jdk == 23                                          && 'yes' || '' }}
      is_main:        ${{ github.ref_name == github.event.repository.default_branch && 'yes' || '' }}
      is_develop:     ${{ github.ref_name == 'develop'                              && 'yes' || '' }}
      is_fork:        ${{ github.event_name == 'pull_request'                       && 'yes' || '' }}

    steps:

    # ================================
    # SHALLOW CLONE
    # ================================
    - name: Shallow clone
      if: ${{ !env.is_latest_jdk || env.is_fork }}
      uses: actions/checkout@v4

    # ================================
    # CHECKOUT
    # ================================
    - name: Checkout git branch
      if: ${{ env.is_latest_jdk && !env.is_fork }}
      uses: actions/checkout@v4
      with:
        # Fetch all history for all tags and branches (recommended by SonarQube)
        fetch-depth: 0

    # ================================
    # VALIDATE GRADLE WRAPPER
    # ================================
    - name: Validate Gradle Wrapper files
      if: ${{ env.is_latest_jdk }}
      uses: gradle/actions/wrapper-validation@v4

    # ================================
    # SET UP JDK
    # ================================
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-package: jdk
        java-version: ${{ matrix.jdk }}

    # ================================
    # SET UP GRADLE
    # ================================
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
        build-scan-terms-of-use-agree: "yes"
        cache-read-only: ${{ !env.is_main && !env.is_develop }}

    # ================================
    # BUILD
    # ================================
    - name: Build
      run: ./gradlew build -x check

    # ================================
    # CHECK
    # ================================
    - name: Check
      run: ./gradlew check

    # ================================
    # COMPATIBILITY REPORT
    # ================================
    - name: Compatibility with previous version
      if: ${{ env.is_latest_jdk }}
      # $GITHUB_STEP_SUMMARY supports content up to a size of 1024k
      run: head -c 1MiB ./api-compatibility/build/report.md >> $GITHUB_STEP_SUMMARY

    # ================================
    # CACHE SONARCLOUD PACKAGES
    # ================================
    - name: Cache SonarCloud packages
      if: ${{ env.is_latest_jdk && !env.is_fork }}
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-sonar
        path: |
          ~/.sonar/cache
        restore-keys: |
          ${{ runner.os }}-sonar

    # ================================
    # ANALYZE WITH SONARCLOUD
    # ================================
    - name: Analyze with SonarCloud
      if: ${{ env.is_latest_jdk && !env.is_fork }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: https://sonarcloud.io
        SONAR_ORGANIZATION: leakyabstractions
      run: ./gradlew sonar

    # ================================
    # PUBLISH SNAPSHOT
    # ================================
    - name: Publish snapshot version
      if: ${{ env.is_latest_jdk && !env.is_fork }}
      env:
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
        JRELEASER_GPG_SECRET_KEY: ${{ secrets.SIGNING_KEY }}
        JRELEASER_GPG_PASSPHRASE: ${{ secrets.SIGNING_PASSWORD }}
        JRELEASER_GITHUB_USERNAME: ${{ secrets.PUBLISH_USERNAME }}
        JRELEASER_GITHUB_TOKEN: ${{ secrets.PUBLISH_PASSWORD }}
        JRELEASER_DEPLOY_MAVEN_NEXUS2_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        JRELEASER_DEPLOY_MAVEN_NEXUS2_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      run: ./gradlew publish jreleaserPublish --info
