
# Publish a new Release
name: Release

on:
  push:
    tags: ['[0-9]+.[0-9]+.[0-9]+.[0-9]+*']

jobs:
  publish:

    name: Publish
    runs-on: ubuntu-latest

    steps:

    # ================================
    # CHECKOUT
    # ================================
    - name: Checkout git tag
      uses: actions/checkout@v4

    # ================================
    # SET UP JDK
    # ================================
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-package: jdk
        java-version: 21

    # ================================
    # SET UP GRADLE
    # ================================
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
        build-scan-terms-of-use-agree: "yes"

    # ================================
    # PUBLISH
    # ================================
    - name: Publish
      env:
        JRELEASER_DISTRIBUTIONS_ACTIVE: RELEASE
        JRELEASER_DEPLOY_ACTIVE: RELEASE
        JRELEASER_GPG_SECRET_KEY: ${{ secrets.SIGNING_KEY }}
        JRELEASER_GPG_PASSPHRASE: ${{ secrets.SIGNING_PASSWORD }}
        JRELEASER_GITHUB_USERNAME: ${{ secrets.PUBLISH_USERNAME }}
        JRELEASER_GITHUB_TOKEN: ${{ secrets.PUBLISH_PASSWORD }}
        JRELEASER_DEPLOY_MAVEN_NEXUS2_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        JRELEASER_DEPLOY_MAVEN_NEXUS2_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        JRELEASER_NEXUS2_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
      run: ./gradlew jreleaserFullRelease --info
